// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8TMF8DX32GBwGiLn8Fd1jtUC0Jy0jRBE',
    appId: '1:1011485387647:web:93d3249cfc5ba570c9c84a',
    messagingSenderId: '1011485387647',
    projectId: 'quickbites-5aa42',
    authDomain: 'quickbites-5aa42.firebaseapp.com',
    storageBucket: 'quickbites-5aa42.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb5Jc5-yP3MP2KA-x-GOutnTNWly815Jg',
    appId: '1:1011485387647:android:696d9d23bbdfad1cc9c84a',
    messagingSenderId: '1011485387647',
    projectId: 'quickbites-5aa42',
    storageBucket: 'quickbites-5aa42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp-B3LWieiKYtyyNhouDf1HIq6T3m11Lo',
    appId: '1:1011485387647:ios:4176348003525cbcc9c84a',
    messagingSenderId: '1011485387647',
    projectId: 'quickbites-5aa42',
    storageBucket: 'quickbites-5aa42.firebasestorage.app',
    iosBundleId: 'guywhocodes.quickbites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp-B3LWieiKYtyyNhouDf1HIq6T3m11Lo',
    appId: '1:1011485387647:ios:4176348003525cbcc9c84a',
    messagingSenderId: '1011485387647',
    projectId: 'quickbites-5aa42',
    storageBucket: 'quickbites-5aa42.firebasestorage.app',
    iosBundleId: 'guywhocodes.quickbites',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8TMF8DX32GBwGiLn8Fd1jtUC0Jy0jRBE',
    appId: '1:1011485387647:web:60befed76772cdf4c9c84a',
    messagingSenderId: '1011485387647',
    projectId: 'quickbites-5aa42',
    authDomain: 'quickbites-5aa42.firebaseapp.com',
    storageBucket: 'quickbites-5aa42.firebasestorage.app',
  );
}
